module.exports = {
    env: {
        REACT_APP_FLWPUBLICKEY: process.env.REACT_APP_FLWPUBLICKEY,
        REACT_APP_ISPROD: process.env.REACT_APP_ISPROD,
        REACT_APP_ANGELSAPIBASE: process.env.REACT_APP_ANGELSAPIBASE,
        REACT_APP_ANGELSRECIPIENTENROLLMENTURL: process.env.REACT_APP_ANGELSRECIPIENTENROLLMENTURL
    }
};